"""initial schema

Revision ID: 154c712d7b1b
Revises:
Create Date: 2026-07-10

Creates all 7 entities from docs/guidelines/entity_model.md: OWNER, PET_TYPE, PET, VISIT,
VETERINARIAN, SPECIALTY, VET_SPECIALTY. Written by hand against the entity model rather than
autogenerated (no SQLAlchemy ORM models exist yet — that's /implement-backend).

Case-insensitive uniqueness of PET (owner_id, name) — UC-007/UC-008 BR-001 — cannot be
expressed as a plain UNIQUE constraint (that's case-sensitive); it's a functional unique index
on (owner_id, lower(name)) instead (architecture.md §2.4).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "154c712d7b1b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "owner",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("first_name", sa.String(50), nullable=False),
        sa.Column("last_name", sa.String(50), nullable=False),
        sa.Column("address", sa.String(255), nullable=False),
        sa.Column("city", sa.String(80), nullable=False),
        sa.Column("telephone", sa.String(10), nullable=False),
    )

    op.create_table(
        "pet_type",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.UniqueConstraint("name", name="uq_pet_type_name"),
    )

    op.create_table(
        "veterinarian",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("first_name", sa.String(50), nullable=False),
        sa.Column("last_name", sa.String(50), nullable=False),
    )

    op.create_table(
        "specialty",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.UniqueConstraint("name", name="uq_specialty_name"),
    )

    op.create_table(
        "pet",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), sa.ForeignKey("owner.id"), nullable=False),
        sa.Column("pet_type_id", sa.BigInteger(), sa.ForeignKey("pet_type.id"), nullable=False),
    )
    op.create_index(
        "uq_pet_owner_id_lower_name",
        "pet",
        ["owner_id", sa.text("lower(name)")],
        unique=True,
    )

    op.create_table(
        "visit",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("pet_id", sa.BigInteger(), sa.ForeignKey("pet.id"), nullable=False),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(500), nullable=False),
    )

    op.create_table(
        "vet_specialty",
        sa.Column("vet_id", sa.BigInteger(), sa.ForeignKey("veterinarian.id"), primary_key=True),
        sa.Column("specialty_id", sa.BigInteger(), sa.ForeignKey("specialty.id"), primary_key=True),
    )


def downgrade() -> None:
    op.drop_table("vet_specialty")
    op.drop_table("visit")
    op.drop_index("uq_pet_owner_id_lower_name", table_name="pet")
    op.drop_table("pet")
    op.drop_table("specialty")
    op.drop_table("veterinarian")
    op.drop_table("pet_type")
    op.drop_table("owner")
